Slightly improve error message for references when "displayProperty" has a typo
This is a fix for o/bug/23491

Could potentially make the error message even more accurate by saying the field doesn't exist. I'm open
to opinions on whether that's worth it.

Old error message:

```
TypeError: Cannot read property 'required' of undefined
    at checkSchemaPropertyIsRequired (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/schema.js:497:53)
    at validateObjectSchema (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/schema.js:479:9)
    at makeObjectSchema2 (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/schema.js:464:5)
    at Object.makeReferenceSchemaFromObjectSchema2 (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/schema.js:559:12)
    at Object.<anonymous> (../../../../../../private/var/folders/Users/DavidWeitzman/src/my-test-pack/schemas.ts:27:32)

    <more lines>
```

New error message:

```
Error: Field "Name" must be marked as required in schema with codaType "reference".
    at assertCondition (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/helpers/ensure.js:82:15)
    at checkSchemaPropertyIsRequired (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/schema.js:498:18)
    at validateObjectSchema (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/schema.js:479:9)
    at makeObjectSchema2 (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/schema.js:464:5)
    at Object.makeReferenceSchemaFromObjectSchema2 (../../../../../../private/var/folders/Users/DavidWeitzman/src/packs-sdk/dist/schema.js:560:12)
    at Object.<anonymous> (../../../../../../private/var/folders/Users/DavidWeitzman/src/my-test-pack/schemas.ts:27:32)
    <more lines>
```